language: python
python:
  - '3.6.7'
install: "pip install -r requirements.txt"
services:
  - postgresql
addons:
  postgresql: "10"
before_script:
  - psql -c "CREATE DATABASE ireporter_test" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres
script: 
  - pytest --cov-report term-missing --cov=./app
after_success:
  - coveralls
cache: pip
